In [3]:
import pandas as pd
from pathlib import Path

# CSV読み込み
df = pd.read_csv("中間発表.csv")

# 数値列を整える
numeric_cols = ["RE24", "WPA", "打点"]

for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0)

# 本塁打列を作る
if "打席結果" in df.columns:
    df["本塁打"] = df["打席結果"].astype(str).str.contains("本塁打|ホームラン|HR").astype(int)
else:
    df["本塁打"] = 0

# summaryを作成
summary = (
    df.groupby(["球団", "打者名"], as_index=False)
    .agg(
        打席数=("打者名", "count"),
        RE24合計=("RE24", "sum"),
        WPA合計=("WPA", "sum"),
        打点合計=("打点", "sum"),
        本塁打合計=("本塁打", "sum"),
    )
)

summary["1打席あたりRE24"] = summary["RE24合計"] / summary["打席数"]
summary["1打席あたりWPA"] = summary["WPA合計"] / summary["打席数"]

summary = summary.sort_values("RE24合計", ascending=False)

display(summary.head(10))

       球団    打者名  打席数  RE24合計     WPA合計  打点合計  本塁打合計  1打席あたりRE24  1打席あたりWPA
16   日本ハム  野村　佑希   20   6.100  0.914363     7      0    0.305000   0.045718
6    ヤクルト    オスナ   13   3.578  0.617753     2      0    0.275231   0.047519
9     ロッテ     ソト   17   3.355 -0.314895     5      0    0.197353  -0.018523
13     巨人  岡本　和真   31   1.916  0.278473     4      0    0.061806   0.008983
19     西武  中村　剛也    4   1.261  0.434562     0      0    0.315250   0.108641
20     阪神  森下　翔太   31   1.240  0.356859     4      0    0.040000   0.011512
4   オリックス  西野　真弘    1   1.012 -0.108702     1      0    1.012000  -0.108702
10    ロッテ   ポランコ    5   0.681 -0.041264     1      0    0.136200  -0.008253
7    ヤクルト   サンタナ   11   0.661  0.091890     1      0    0.060091   0.008354
11     中日  山本　泰寛    1   0.106  0.000000     0      0    0.106000   0.000000

In [4]:
re24_top10 = summary.sort_values("RE24合計", ascending=False).head(10)

display(
    re24_top10[
        ["球団", "打者名", "打席数", "RE24合計", "WPA合計", "打点合計", "本塁打合計", "1打席あたりRE24"]
    ]
)

       球団    打者名  打席数  RE24合計     WPA合計  打点合計  本塁打合計  1打席あたりRE24
16   日本ハム  野村　佑希   20   6.100  0.914363     7      0    0.305000
6    ヤクルト    オスナ   13   3.578  0.617753     2      0    0.275231
9     ロッテ     ソト   17   3.355 -0.314895     5      0    0.197353
13     巨人  岡本　和真   31   1.916  0.278473     4      0    0.061806
19     西武  中村　剛也    4   1.261  0.434562     0      0    0.315250
20     阪神  森下　翔太   31   1.240  0.356859     4      0    0.040000
4   オリックス  西野　真弘    1   1.012 -0.108702     1      0    1.012000
10    ロッテ   ポランコ    5   0.681 -0.041264     1      0    0.136200
7    ヤクルト   サンタナ   11   0.661  0.091890     1      0    0.060091
11     中日  山本　泰寛    1   0.106  0.000000     0      0    0.106000

In [5]:
display(
    summary.sort_values("RE24合計", ascending=False)
    .head(10)[
        ["球団", "打者名", "打席数", "RE24合計", "WPA合計", "打点合計", "本塁打合計", "1打席あたりRE24"]
    ]
)

       球団    打者名  打席数  RE24合計     WPA合計  打点合計  本塁打合計  1打席あたりRE24
16   日本ハム  野村　佑希   20   6.100  0.914363     7      0    0.305000
6    ヤクルト    オスナ   13   3.578  0.617753     2      0    0.275231
9     ロッテ     ソト   17   3.355 -0.314895     5      0    0.197353
13     巨人  岡本　和真   31   1.916  0.278473     4      0    0.061806
19     西武  中村　剛也    4   1.261  0.434562     0      0    0.315250
20     阪神  森下　翔太   31   1.240  0.356859     4      0    0.040000
4   オリックス  西野　真弘    1   1.012 -0.108702     1      0    1.012000
10    ロッテ   ポランコ    5   0.681 -0.041264     1      0    0.136200
7    ヤクルト   サンタナ   11   0.661  0.091890     1      0    0.060091
11     中日  山本　泰寛    1   0.106  0.000000     0      0    0.106000

In [6]:
wpa_top10 = summary.sort_values("WPA合計", ascending=False).head(10)

display(
    wpa_top10[
        ["球団", "打者名", "打席数", "RE24合計", "WPA合計", "打点合計", "本塁打合計", "1打席あたりWPA"]
    ]
)

        球団     打者名  打席数  RE24合計     WPA合計  打点合計  本塁打合計  1打席あたりWPA
16    日本ハム   野村　佑希   20   6.100  0.914363     7      0   0.045718
6     ヤクルト     オスナ   13   3.578  0.617753     2      0   0.047519
19      西武   中村　剛也    4   1.261  0.434562     0      0   0.108641
3    オリックス  杉本　裕太郎   21  -0.912  0.382702     3      0   0.018224
20      阪神   森下　翔太   31   1.240  0.356859     4      0   0.011512
13      巨人   岡本　和真   31   1.916  0.278473     4      0   0.008983
0     DeNA  オースティン   21  -1.009  0.164072     1      0   0.007813
7     ヤクルト    サンタナ   11   0.661  0.091890     1      0   0.008354
5   ソフトバンク   山川　穂高   21  -2.195  0.010095     1      0   0.000481
2     DeNA   蝦名　達夫    1  -0.008  0.000000     1      0   0.000000

In [7]:
rbi_top10 = summary.sort_values("打点合計", ascending=False).head(10)

display(
    rbi_top10[
        ["球団", "打者名", "打席数", "RE24合計", "WPA合計", "打点合計", "本塁打合計", "1打席あたりRE24"]
    ]
)

        球団     打者名  打席数  RE24合計     WPA合計  打点合計  本塁打合計  1打席あたりRE24
16    日本ハム   野村　佑希   20   6.100  0.914363     7      0    0.305000
9      ロッテ      ソト   17   3.355 -0.314895     5      0    0.197353
13      巨人   岡本　和真   31   1.916  0.278473     4      0    0.061806
20      阪神   森下　翔太   31   1.240  0.356859     4      0    0.040000
3    オリックス  杉本　裕太郎   21  -0.912  0.382702     3      0   -0.043429
18      西武   セデーニョ   13  -0.520 -0.515294     2      0   -0.040000
6     ヤクルト     オスナ   13   3.578  0.617753     2      0    0.275231
5   ソフトバンク   山川　穂高   21  -2.195  0.010095     1      0   -0.104524
14      広島    モンテロ   12  -1.933 -0.394872     1      0   -0.161083
0     DeNA  オースティン   21  -1.009  0.164072     1      0   -0.048048

In [8]:
# ⑥ 打点とRE24の相関を確認
corr_rbi_re24 = summary["打点合計"].corr(summary["RE24合計"])

print("打点合計とRE24合計の相関係数:", corr_rbi_re24)

打点合計とRE24合計の相関係数: 0.7335131145906069

In [9]:
corr_re24_wpa = summary["RE24合計"].corr(summary["WPA合計"])

print("RE24合計とWPA合計の相関係数:", corr_re24_wpa)

RE24合計とWPA合計の相関係数: 0.6429476346505378

NameError: name 'df' is not defined